apiVersion: v1
kind: Service
metadata:
  name: swappdb
  labels:
    {{- include "swapp-db.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  clusterIP: None
  selector:
    {{- include "swapp-db.selectorLabels" . | nindent 4 }}
