apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swapp-gateway.fullname" . }}
  labels:
    {{- include "swapp-gateway.labels" . | nindent 4 }}
data:
  mongoHost: swapp-swapp-db
  registrationUrl: http://swapp-swapp-auth:8082/
  adsUrl: http://swapp-swapp-ads:8083/
