spring:
  cloud:
    function:
      definition: consumer;onReceive
    stream:
      bindings:
         consumer-in-0:
            destination: "likequeue"
            group: consumer
            consumer:
              max-attempts: 1
         onReceive-in-0:
            destination: "annunciqueue"
            group: consumer
            consumer:
              max-attempts: 1
  data:
    mongodb:
      authentication-database: admin
      username: root
      database: demodb
      password: example
      port: 27017
      host: 127.0.0.1
server:
  port: 8084
  shutdown: graceful