apiVersion: v1
kind: Service
metadata:
  name: {{ include "swapp-queue.fullname" . }}
  labels:
    {{- include "swapp-queue.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rabbitmq }}
      targetPort: rabbitmq
      protocol: TCP
      name: rabbitmq
    - port: {{ .Values.service.management }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "swapp-queue.selectorLabels" . | nindent 4 }}
