{{- if .Values.ingress.frontend.enabled -}}
{{- $fullName := include "swapp.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "swapp.labels" . | nindent 4 }}
spec:
  rules:
    - host: swapp.mastercc.hpc4ai.unito.it
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swapp-swapp-frontend
                port:
                  name: http
{{- end }}
