spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      database: demodb
      password: example
      port: 27017
      host: 127.0.0.1
server:
  port: 8082
  error:
    include-message: always
  shutdown: graceful

