apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swapp-ads.fullname" . }}
  labels:
    {{- include "swapp-ads.labels" . | nindent 4 }}
data:
  mongoHost: swapp-swapp-db
  rabbitHost: swapp-swapp-queue
